




.build_ano/mega2560/src/RobotMain.cpp : src/RobotMain.ino
	@mkdir -p .build_ano/mega2560/src
	@echo [93msrc/RobotMain.ino[0m
	@/usr/local/bin/ano preproc --source-dir src  -o $@ $^


all : .build_ano/mega2560/src/RobotMain.cpp
	@true

